export const initialExercises = [
  // CHEST
  {
    name: 'Barbell Flat Bench Press',
    muscleGroup: 'Chest',
    difficulty: 'Intermediate',
    equipment: 'Barbell',
    instructions: 'Lie on the bench with eyes under the bar. Grip bar with wrists straight, lower with control to mid-chest, and press straight upward firmly.',
    imageUrl: '/exercises/bench-press.svg',
  },
  {
    name: 'Incline Dumbbell Press',
    muscleGroup: 'Chest',
    difficulty: 'Intermediate',
    equipment: 'Dumbbells',
    instructions: 'Set bench to 30 degrees. Hold dumbbells at shoulder level, press upward with a smooth arc, and lower under control.',
    imageUrl: '/exercises/incline-press.svg',
  },
  {
    name: 'Standard Push-Ups',
    muscleGroup: 'Chest',
    difficulty: 'Beginner',
    equipment: 'Bodyweight',
    instructions: 'Maintain a rigid straight plank line from head to heels. Lower chest until elbows reach 90 degrees and push through palms.',
    imageUrl: '/exercises/pushup.svg',
  },
  {
    name: 'Dumbbell Chest Flyes',
    muscleGroup: 'Chest',
    difficulty: 'Beginner',
    equipment: 'Dumbbells',
    instructions: 'Lie flat on bench with slight bend in elbows. Open arms wide until chest stretches, then squeeze weights back to top center.',
    imageUrl: '/exercises/bench-press.svg',
  },

  // BACK
  {
    name: 'Wide-Grip Lat Pulldown',
    muscleGroup: 'Back',
    difficulty: 'Beginner',
    equipment: 'Cable Machine',
    instructions: 'Sit tall with thighs locked under pads. Grip bar wide, pull down toward upper chest squeezing shoulder blades down and back.',
    imageUrl: '/exercises/lat-pulldown.svg',
  },
  {
    name: 'Bent-Over Barbell Row',
    muscleGroup: 'Back',
    difficulty: 'Intermediate',
    equipment: 'Barbell',
    instructions: 'Hinge hips forward at a 45-degree angle with a flat back. Pull barbell into lower abdomen and lower under control.',
    imageUrl: '/exercises/cable-row.svg',
  },
  {
    name: 'Seated Cable Row',
    muscleGroup: 'Back',
    difficulty: 'Beginner',
    equipment: 'Cable Machine',
    instructions: 'Sit upright with knees slightly bent. Pull handle smoothly into belly button while keeping torso tall and shoulders retracted.',
    imageUrl: '/exercises/cable-row.svg',
  },
  {
    name: 'Conventional Barbell Deadlift',
    muscleGroup: 'Back',
    difficulty: 'Advanced',
    equipment: 'Barbell',
    instructions: 'Stand with feet hip-width, grip bar outside knees. Keep spine neutral, brace core, and drive through heels to full standing lockout.',
    imageUrl: '/exercises/deadlift.svg',
  },

  // LEGS
  {
    name: 'Barbell Back Squats',
    muscleGroup: 'Legs',
    difficulty: 'Intermediate',
    equipment: 'Barbell',
    instructions: 'Place bar across upper traps. Inhale, brace core, break at hips and knees simultaneously until thighs are parallel to ground, then drive up.',
    imageUrl: '/exercises/squats.svg',
  },
  {
    name: 'Dumbbell Goblet Squats',
    muscleGroup: 'Legs',
    difficulty: 'Beginner',
    equipment: 'Dumbbells',
    instructions: 'Cup a dumbbell against your chest. Keep torso upright and squat deeply between your knees with control.',
    imageUrl: '/exercises/squats.svg',
  },
  {
    name: 'Romanian Deadlifts (RDL)',
    muscleGroup: 'Legs',
    difficulty: 'Intermediate',
    equipment: 'Barbell',
    instructions: 'Hold bar at hips with knees slightly unlocked. Push hips back as far as possible until hamstrings stretch, then return forward.',
    imageUrl: '/exercises/deadlift.svg',
  },
  {
    name: 'Walking Dumbbell Lunges',
    muscleGroup: 'Legs',
    difficulty: 'Beginner',
    equipment: 'Dumbbells',
    instructions: 'Step forward into a lunge until trailing knee approaches floor. Drive through front heel to step directly into the next lunge.',
    imageUrl: '/exercises/lunges.svg',
  },
  {
    name: 'Leg Press Machine',
    muscleGroup: 'Legs',
    difficulty: 'Beginner',
    equipment: 'Machine',
    instructions: 'Sit firmly in seat with feet shoulder-width on platform. Release safety locks, lower sled under control, and press back without locking knees.',
    imageUrl: '/exercises/leg-press.svg',
  },

  // SHOULDERS
  {
    name: 'Overhead Dumbbell Shoulder Press',
    muscleGroup: 'Shoulders',
    difficulty: 'Beginner',
    equipment: 'Dumbbells',
    instructions: 'Sit or stand tall. Press dumbbells straight overhead from ear height without overarching your lower spine.',
    imageUrl: '/exercises/shoulder-press.svg',
  },
  {
    name: 'Dumbbell Lateral Raises',
    muscleGroup: 'Shoulders',
    difficulty: 'Beginner',
    equipment: 'Dumbbells',
    instructions: 'Stand tall with dumbbells at sides. Raise arms outward to shoulder level with slight elbow bend and lower smoothly.',
    imageUrl: '/exercises/lateral-raise.svg',
  },
  {
    name: 'Standing Barbell Overhead Press',
    muscleGroup: 'Shoulders',
    difficulty: 'Advanced',
    equipment: 'Barbell',
    instructions: 'Hold bar at clavicles, tighten glutes and core, and press vertically overhead in a straight path locking out at the top.',
    imageUrl: '/exercises/shoulder-press.svg',
  },

  // ARMS
  {
    name: 'Standing Barbell Bicep Curls',
    muscleGroup: 'Arms',
    difficulty: 'Beginner',
    equipment: 'Barbell',
    instructions: 'Keep elbows tucked beside ribs. Curl barbell upward using only bicep tension, avoiding swinging your torso.',
    imageUrl: '/exercises/bicep-curl.svg',
  },
  {
    name: 'Cable Triceps Rope Pushdown',
    muscleGroup: 'Arms',
    difficulty: 'Beginner',
    equipment: 'Cable Machine',
    instructions: 'Pin elbows against your sides. Push rope down until arms are fully extended and spread rope ends apart at the bottom.',
    imageUrl: '/exercises/tricep-pushdown.svg',
  },
  {
    name: 'Parallel Bar Dips',
    muscleGroup: 'Arms',
    difficulty: 'Advanced',
    equipment: 'Bodyweight',
    instructions: 'Lower body between parallel bars until elbows reach 90 degrees. Press upward through palms back to arm extension.',
    imageUrl: '/exercises/tricep-pushdown.svg',
  },

  // CORE
  {
    name: 'Isometric Core Plank',
    muscleGroup: 'Core',
    difficulty: 'Beginner',
    equipment: 'Bodyweight',
    instructions: 'Rest on forearms and toes. Keep spine perfectly straight, brace abs firmly, and maintain steady deep breaths.',
    imageUrl: '/exercises/plank.svg',
  },
  {
    name: 'Dynamic Mountain Climbers',
    muscleGroup: 'Core',
    difficulty: 'Beginner',
    equipment: 'Bodyweight',
    instructions: 'From high plank position, drive knees alternately towards chest in a rapid, controlled rhythmic cadence.',
    imageUrl: '/exercises/plank.svg',
  },
  {
    name: 'Hanging Knee Raises',
    muscleGroup: 'Core',
    difficulty: 'Intermediate',
    equipment: 'Bodyweight',
    instructions: 'Hang from pull-up bar. Without swinging, raise knees towards chest using lower abdominals, hold briefly and lower.',
    imageUrl: '/exercises/plank.svg',
  },
];
